/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorGeneral;

/**
 *
 * @author Ever Hernández
 */
public class Administrador extends javax.swing.JFrame {
private final ControladorGeneral controladorGeneral = new ControladorGeneral();
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Repuestos = new javax.swing.JButton();
        Servicios = new javax.swing.JButton();
        Repuestos2 = new javax.swing.JButton();
        Repuestos3 = new javax.swing.JButton();
        Repuestos4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Repuestos.setBackground(new java.awt.Color(205, 51, 51));
        Repuestos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Repuestos.setForeground(new java.awt.Color(255, 255, 255));
        Repuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconore.png"))); // NOI18N
        Repuestos.setText("Repuestos");
        Repuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepuestosActionPerformed(evt);
            }
        });
        jPanel1.add(Repuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, 40));

        Servicios.setBackground(new java.awt.Color(205, 51, 51));
        Servicios.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Servicios.setForeground(new java.awt.Color(255, 255, 255));
        Servicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconose.png"))); // NOI18N
        Servicios.setText("Servicios");
        Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(Servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 40));

        Repuestos2.setBackground(new java.awt.Color(205, 51, 51));
        Repuestos2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Repuestos2.setForeground(new java.awt.Color(255, 255, 255));
        Repuestos2.setText("Cliente y automoviles");
        Repuestos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Repuestos2ActionPerformed(evt);
            }
        });
        jPanel1.add(Repuestos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 30));

        Repuestos3.setBackground(new java.awt.Color(205, 51, 51));
        Repuestos3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Repuestos3.setForeground(new java.awt.Color(255, 255, 255));
        Repuestos3.setText("Progreso de autos");
        Repuestos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Repuestos3ActionPerformed(evt);
            }
        });
        jPanel1.add(Repuestos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 190, 30));

        Repuestos4.setBackground(new java.awt.Color(205, 51, 51));
        Repuestos4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Repuestos4.setForeground(new java.awt.Color(255, 255, 255));
        Repuestos4.setText("Reportes");
        Repuestos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Repuestos4ActionPerformed(evt);
            }
        });
        jPanel1.add(Repuestos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RepuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepuestosActionPerformed
        Repuestos rep = new Repuestos(controladorGeneral);
        rep.setVisible(true);
    }//GEN-LAST:event_RepuestosActionPerformed

    private void ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiciosActionPerformed
        Servicios serv = new Servicios(controladorGeneral);
        serv.setVisible(true);
    }//GEN-LAST:event_ServiciosActionPerformed

    private void Repuestos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Repuestos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Repuestos2ActionPerformed

    private void Repuestos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Repuestos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Repuestos3ActionPerformed

    private void Repuestos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Repuestos4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Repuestos4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Repuestos;
    private javax.swing.JButton Repuestos2;
    private javax.swing.JButton Repuestos3;
    private javax.swing.JButton Repuestos4;
    private javax.swing.JButton Servicios;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
