/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Bitacora;

/**
 *
 * @author Ever Hernández
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Registrodeauto = new javax.swing.JButton();
        verauto = new javax.swing.JButton();
        verprogreso = new javax.swing.JButton();
        factura = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registrodeauto.setBackground(new java.awt.Color(205, 51, 51));
        Registrodeauto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Registrodeauto.setForeground(new java.awt.Color(255, 255, 255));
        Registrodeauto.setText("Registrar automovil");
        Registrodeauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrodeautoActionPerformed(evt);
            }
        });
        jPanel1.add(Registrodeauto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, 40));

        verauto.setBackground(new java.awt.Color(205, 51, 51));
        verauto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        verauto.setForeground(new java.awt.Color(255, 255, 255));
        verauto.setText("Ver mis automovil");
        verauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verautoActionPerformed(evt);
            }
        });
        jPanel1.add(verauto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 200, 40));

        verprogreso.setBackground(new java.awt.Color(205, 51, 51));
        verprogreso.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        verprogreso.setForeground(new java.awt.Color(255, 255, 255));
        verprogreso.setText("Ver Progreso");
        verprogreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verprogresoActionPerformed(evt);
            }
        });
        jPanel1.add(verprogreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 150, 40));

        factura.setBackground(new java.awt.Color(205, 51, 51));
        factura.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        factura.setForeground(new java.awt.Color(255, 255, 255));
        factura.setText("Facturas");
        factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaActionPerformed(evt);
            }
        });
        jPanel1.add(factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 120, 40));

        cerrar.setBackground(new java.awt.Color(205, 51, 51));
        cerrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setText("Cerrar Sesion");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrodeautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrodeautoActionPerformed
        RegistroAuto panta1 = new RegistroAuto();
        panta1.setVisible(true);
        Bitacora.General("Administrador", "Preciono boton Repuestos", "Exito", "ingresar datos");
    }//GEN-LAST:event_RegistrodeautoActionPerformed

    private void verautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verautoActionPerformed
        
    }//GEN-LAST:event_verautoActionPerformed

    private void verprogresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verprogresoActionPerformed
        
    }//GEN-LAST:event_verprogresoActionPerformed

    private void facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaActionPerformed
        
    }//GEN-LAST:event_facturaActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.setVisible(false);       
    }//GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrodeauto;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton factura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton verauto;
    private javax.swing.JButton verprogreso;
    // End of variables declaration//GEN-END:variables
}
