/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Bitacora;
import Modelo.Mo_Nuevosclientes;
import Modelo.Mo_Nuevosclientes.Nuevosvehiculos;
import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ever Hernández
 */
public class RegistroAuto extends javax.swing.JFrame {
private String nombreUsuario;
private Vector<Nuevosvehiculos> listaVehiculos; // Vector para almacenar los automóviles
private String rutaImagenSeleccionada; // Ruta de la imagen seleccionada

    /**
     * Creates new form RegistroAuto
     */
    public RegistroAuto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.nombreUsuario = nombreUsuario;
        this.nombreUsuario = nombreUsuario;
        listaVehiculos = new Vector<>(); // Inicializar el vector
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btagregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        texplaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        texmarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        texmodelo = new javax.swing.JTextField();
        Regresar = new javax.swing.JButton();
        Ingresar = new javax.swing.JButton();
        Lblimagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btagregar.setBackground(new java.awt.Color(205, 51, 51));
        btagregar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btagregar.setForeground(new java.awt.Color(255, 255, 255));
        btagregar.setText("Agregar foto");
        btagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btagregarActionPerformed(evt);
            }
        });
        jPanel1.add(btagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 150, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Foto del carro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Placa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));
        jPanel1.add(texplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Marca");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        jPanel1.add(texmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 190, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Modelo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        jPanel1.add(texmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 190, -1));

        Regresar.setBackground(new java.awt.Color(205, 51, 51));
        Regresar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Regresar.setForeground(new java.awt.Color(255, 255, 255));
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 150, 40));

        Ingresar.setBackground(new java.awt.Color(205, 51, 51));
        Ingresar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 150, 40));
        jPanel1.add(Lblimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 280, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btagregarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes JPG", "jpg"));
        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            rutaImagenSeleccionada = fileChooser.getSelectedFile().getAbsolutePath();
            ImageIcon icon = new ImageIcon(rutaImagenSeleccionada);

            // Escalar la imagen para ajustarla al tamaño del JLabel Lblimagen
            Image image = icon.getImage().getScaledInstance(Lblimagen.getWidth(), Lblimagen.getHeight(), Image.SCALE_SMOOTH);

            // Establecer la imagen en el JLabel Lblimagen
            Lblimagen.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_btagregarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        
        Bitacora.General("Cliente", "Preciono boton Regresar", "Exito", "Ingreso el e");
        this.setVisible(false);
    }//GEN-LAST:event_RegresarActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        try {
            String placa = texplaca.getText();
            String marca = texmarca.getText();
            String modelo = texmodelo.getText();

            if (placa.isEmpty() || marca.isEmpty() || modelo.isEmpty() || rutaImagenSeleccionada == null) {
                JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos y selecciona una imagen.");
                return;
            }

            // Mover la imagen seleccionada al paquete Imagenes
            String rutaDestinoImagen = moverImagen(rutaImagenSeleccionada);

            // Crear un nuevo vehículo
            Nuevosvehiculos vehiculo = new Mo_Nuevosclientes(0, "", "", "", "").new Nuevosvehiculos(placa, marca, modelo, rutaDestinoImagen);
            listaVehiculos.add(vehiculo);

            // Guardar datos en el archivo .tmca
            guardarDatosEnArchivo();

            JOptionPane.showMessageDialog(this, "Datos guardados correctamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar datos: " + e.getMessage());
        }
    }//GEN-LAST:event_IngresarActionPerformed

    private String moverImagen(String rutaOrigen) throws IOException {
        // Crear la carpeta Imagenes si no existe
        File carpetaImagenes = new File("src/Imagenes");
        if (!carpetaImagenes.exists()) {
            carpetaImagenes.mkdirs();
        }

        // Copiar la imagen al paquete Imagenes
        File imagenOrigen = new File(rutaOrigen);
        File imagenDestino = new File(carpetaImagenes, imagenOrigen.getName());
        Files.copy(imagenOrigen.toPath(), imagenDestino.toPath(), StandardCopyOption.REPLACE_EXISTING);

        // Retornar la ruta relativa de la imagen copiada
        return "src/Imagenes/" + imagenOrigen.getName();
    }

    
    private void guardarDatosEnArchivo() throws IOException {
        String nombreArchivo = "C:\\Users\\Ever Hernández\\Desktop\\Clienteyautomovil.tmca";
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(nombreArchivo, true))) {

        // Obtener información básica del cliente desde la sesión o campos
        String identificador = "12345"; // Reemplazar por el identificador real del cliente
        String nombreCompleto = "Ever Hernández"; // Reemplazar por el nombre real del cliente
        String usuario = Bitacora.Sesion.getNombreUsuario(); // Obtener el nombre del usuario desde la sesión
        String contrasena = "1234"; // Reemplazar por la contraseña real (si corresponde)
        String tipoCliente = "Cliente Regular"; // O el tipo correspondiente

        // Crear la línea base del cliente
        String lineaCliente = identificador + "-" + nombreCompleto + "-" + usuario + "-" + contrasena + "-" + tipoCliente;

        // Agregar información de los vehículos
        StringBuilder vehiculosInfo = new StringBuilder(); // Para agregar múltiples vehículos
        for (Nuevosvehiculos vehiculo : listaVehiculos) {
            String datosVehiculo = vehiculo.getPlaca() + ","
                    + vehiculo.getMarca() + ","
                    + vehiculo.getModelo() + ","
                    + vehiculo.getImagen();
            if (vehiculosInfo.length() > 0) {
                vehiculosInfo.append(";"); // Separador entre vehículos
            }
            vehiculosInfo.append(datosVehiculo);
        }

        // Línea final que se escribe en el archivo
        String lineaFinal = lineaCliente + "-" + vehiculosInfo.toString();

        // Escribir en el archivo
        writer.write(lineaFinal);
        writer.newLine();

        // Limpiar la lista y los campos después de guardar
        listaVehiculos.clear();
        texplaca.setText("");
        texmarca.setText("");
        texmodelo.setText("");
        rutaImagenSeleccionada = null;
        Lblimagen.setIcon(null); // Limpiar la imagen del JLabel
    }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAuto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JLabel Lblimagen;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton btagregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField texmarca;
    private javax.swing.JTextField texmodelo;
    private javax.swing.JTextField texplaca;
    // End of variables declaration//GEN-END:variables
}
