/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorGeneral;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import Modelo.Mo_inventario;
import Controlador.RepuestoControlador;

/**
 *
 * @author Ever Hernández
 */
public class Repuestos extends javax.swing.JFrame {

    private Object route;
    private ControladorGeneral controladorGeneral;
    private Mo_inventario inventario;
    private RepuestoControlador controlador;
    private String rutaArchivoActual = null;

    /**
     * Creates new form Repuestos
     */
    public Repuestos(ControladorGeneral controladorGeneral) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controladorGeneral = controladorGeneral;
        this.inventario = controladorGeneral.getInventario();
        this.controlador = controladorGeneral.getRepuestoControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bt_regresar = new javax.swing.JButton();
        Ruta = new javax.swing.JTextField();
        Bt_Abrirarchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Contenido = new javax.swing.JTextArea();
        Bt_Guardar = new javax.swing.JButton();
        Text2 = new javax.swing.JTextField();
        Text4 = new javax.swing.JTextField();
        Text1 = new javax.swing.JTextField();
        Text5 = new javax.swing.JTextField();
        Text3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Bt_agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bt_regresar.setBackground(new java.awt.Color(205, 51, 51));
        Bt_regresar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Bt_regresar.setForeground(new java.awt.Color(255, 255, 255));
        Bt_regresar.setText("Regresar");
        Bt_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_regresarActionPerformed(evt);
            }
        });
        jPanel1.add(Bt_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 150, -1));

        Ruta.setEditable(false);
        Ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutaActionPerformed(evt);
            }
        });
        jPanel1.add(Ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, -1));

        Bt_Abrirarchivo.setBackground(new java.awt.Color(205, 51, 51));
        Bt_Abrirarchivo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Bt_Abrirarchivo.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Abrirarchivo.setText("Abrir archivo");
        Bt_Abrirarchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AbrirarchivoActionPerformed(evt);
            }
        });
        jPanel1.add(Bt_Abrirarchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        Contenido.setColumns(20);
        Contenido.setRows(5);
        jScrollPane1.setViewportView(Contenido);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 490, 150));

        Bt_Guardar.setBackground(new java.awt.Color(205, 51, 51));
        Bt_Guardar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Bt_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Guardar.setText("Guardar  Cambios");
        Bt_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Bt_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        Text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text2ActionPerformed(evt);
            }
        });
        jPanel1.add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, -1));

        Text4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text4ActionPerformed(evt);
            }
        });
        jPanel1.add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 90, -1));

        Text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text1ActionPerformed(evt);
            }
        });
        jPanel1.add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, -1));

        Text5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text5ActionPerformed(evt);
            }
        });
        jPanel1.add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 90, -1));

        Text3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text3ActionPerformed(evt);
            }
        });
        jPanel1.add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 90, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Marca");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 70, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Modelo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 70, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Existencia");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 90, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Precio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 70, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, -1));

        Bt_agregar.setBackground(new java.awt.Color(205, 51, 51));
        Bt_agregar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Bt_agregar.setForeground(new java.awt.Color(255, 255, 255));
        Bt_agregar.setText("Agregar datos");
        Bt_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(Bt_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_regresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_Bt_regresarActionPerformed

    private void RutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RutaActionPerformed

    private void Bt_AbrirarchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AbrirarchivoActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);//Indicamos que abra solamente archivos
        
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto", "txt", "tmr");//Solamente acepta archivos de estas extenciones
        fc.setFileFilter(filtro);
        
        int res = fc.showOpenDialog(this);
        if(res != JFileChooser.CANCEL_OPTION){// Abrio un archivo
            File name = fc.getSelectedFile();
            
            if((name == null) || name.getName().equals("")){
                JOptionPane.showMessageDialog(this, "Error de archivo");
            }else {
                Ruta.setText(name.getAbsolutePath());//Nos muestra la ruta completa de donde esta el archivo
                try {
                    muestraContenido(name.getAbsolutePath());
                } catch (IOException ex) {
                    Logger.getLogger(Repuestos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_Bt_AbrirarchivoActionPerformed

    private void Bt_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_GuardarActionPerformed
        if (rutaArchivoActual == null) {
            JOptionPane.showMessageDialog(this, "Primero debes abrir un archivo.");
            return;
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(rutaArchivoActual))) {
            writer.write(Contenido.getText());
            JOptionPane.showMessageDialog(this, "Archivo actualizado correctamente.");
            
            controlador.actualizarInventarioDesdeTexto(Contenido.getText());
            
            System.out.println("Contenido en memoria:");
            for (int i = 0; i < controladorGeneral.getInventario().getCantidad(); i++) {
            System.out.println(controladorGeneral.getInventario().getRepuestos()[i]);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + e.getMessage());
        }
    }

    /*
    }//GEN-LAST:event_Bt_GuardarActionPerformed
    */  
    private void Text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text4ActionPerformed

    private void Text5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text5ActionPerformed

    private void Text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text1ActionPerformed

    private void Text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text2ActionPerformed

    private void Text3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text3ActionPerformed

    private void Bt_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_agregarActionPerformed
        String nombre = Text1.getText().trim();
    String marca = Text2.getText().trim();
    String modelo = Text3.getText().trim();
    String existenciaStr = Text4.getText().trim();
    String precioStr = Text5.getText().trim();

    // Validación básica
    if (nombre.isEmpty() || marca.isEmpty() || modelo.isEmpty() || existenciaStr.isEmpty() || precioStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos.");
        return;
    }

    try {
        int existencias = Integer.parseInt(existenciaStr);
        double precio = Double.parseDouble(precioStr);

        // Armar línea
        String nuevaLinea = nombre + "-" + marca + "-" + modelo + "-" + existencias + "-" + precio;

        // Agregar al JTextArea
        Contenido.append(nuevaLinea + "\n");

        // Limpiar campos
        Text1.setText("");
        Text2.setText("");
        Text3.setText("");
        Text4.setText("");
        Text5.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Existencias debe ser un número entero y precio un número decimal.");
    }
    }//GEN-LAST:event_Bt_agregarActionPerformed

        public void muestraContenido(String name) throws IOException {
        rutaArchivoActual = name;

        BufferedReader reader = new BufferedReader(new FileReader(name));
        Contenido.setText("");
        String linea;
        while ((linea = reader.readLine()) != null) {
            Contenido.append(linea + "\n");
        }
        reader.close();

        controlador.cargarDesdeArchivo(name);     
}
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Abrirarchivo;
    private javax.swing.JButton Bt_Guardar;
    private javax.swing.JButton Bt_agregar;
    private javax.swing.JButton Bt_regresar;
    private javax.swing.JTextArea Contenido;
    private javax.swing.JTextField Ruta;
    private javax.swing.JTextField Text1;
    private javax.swing.JTextField Text2;
    private javax.swing.JTextField Text3;
    private javax.swing.JTextField Text4;
    private javax.swing.JTextField Text5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}

