/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Bitacora;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.*;
import java.util.Vector;
/**
 *
 * @author Ever Hernández
 */
public class Verautomovil extends javax.swing.JFrame {
    private DefaultTableModel tableModel; // Modelo para JTable
    private Vector<String[]> vehiculosCliente; // Vector para almacenar los vehículos del cliente actual
    /**
     * Creates new form Verautomovil
     */
    public Verautomovil() {
        initComponents();
        this.setLocationRelativeTo(null);
        vehiculosCliente = new Vector<>(); // Inicializar el vector
        tableModel = (DefaultTableModel) contenedordatos.getModel(); // Obtener el modelo del JTable

        cargarDatosCliente();
    }
    
    private void cargarDatosCliente() {
         // LIMPIAR DATOS ANTERIORES DEL JTable Y JComboBox
    tableModel.setRowCount(0); // Eliminar todas las filas del JTable
    listadeplaca.removeAllItems(); // Limpiar el JComboBox
    vehiculosCliente.clear(); // Limpiar el vector

    try {
        // Obtener el nombre del usuario desde la sesión
        String nombreUsuario = Bitacora.Sesion.getNombreUsuario();
        System.out.println("Cargando datos para el usuario: " + nombreUsuario); // Depuración

        // Ruta del archivo donde están almacenados los datos
        String rutaArchivo = "C:\\Users\\Ever Hernández\\Desktop\\Clienteyautomovil.tmca";
        File archivo = new File(rutaArchivo);

        // Validar si el archivo existe
        if (!archivo.exists()) {
            JOptionPane.showMessageDialog(this, "El archivo de datos no existe: " + rutaArchivo);
            return;
        }

        // Leer el archivo línea por línea
        BufferedReader br = new BufferedReader(new FileReader(archivo));
        String linea;
        while ((linea = br.readLine()) != null) {
            System.out.println("Línea leída: " + linea); // Depuración

            // Dividir la línea en partes (separadas por "-")
            String[] partes = linea.split("-");
            if (partes.length >= 6 && partes[2].equals(nombreUsuario)) {
                System.out.println("Datos para el usuario coinciden: " + linea); // Depuración

                // Obtener la lista de vehículos (separados por ";")
                String[] vehiculos = partes[5].split(";");
                for (String vehiculo : vehiculos) {
                    String[] datosVehiculo = vehiculo.split(","); // Datos del vehículo: placa, marca, modelo, imagen
                    if (datosVehiculo.length == 4) {
                        System.out.println("Vehículo procesado: " + vehiculo); // Depuración

                        // Agregar al vector, JTable y JComboBox
                        vehiculosCliente.add(datosVehiculo);
                        tableModel.addRow(new Object[]{datosVehiculo[0], datosVehiculo[1], datosVehiculo[2]});
                        listadeplaca.addItem(datosVehiculo[0]);
                    } else {
                        System.out.println("Formato de datos del vehículo inválido: " + vehiculo); // Depuración
                    }
                }
            } else {
                System.out.println("La línea no pertenece al usuario actual o tiene formato inválido: " + linea); // Depuración
            }
        }
        br.close();
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar los datos del cliente: " + e.getMessage());
    }
    }
    
    private void mostrarImagenVehiculo(String placaSeleccionada) {
        for (String[] vehiculo : vehiculosCliente) {
            if (vehiculo[0].equals(placaSeleccionada)) { // Buscar el vehículo por la placa
                String rutaImagen = vehiculo[3]; // Ruta de la imagen
                ImageIcon icon = new ImageIcon(rutaImagen);
                Image image = icon.getImage().getScaledInstance(Lblimagen.getWidth(), Lblimagen.getHeight(), Image.SCALE_SMOOTH);
                Lblimagen.setIcon(new ImageIcon(image)); // Mostrar la imagen en el JLabel
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenedordatos = new javax.swing.JTable();
        registrarse2 = new javax.swing.JButton();
        Lblimagen = new javax.swing.JLabel();
        listadeplaca = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        contenedordatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Placa", "Marca", "Modelo"
            }
        ));
        jScrollPane1.setViewportView(contenedordatos);

        registrarse2.setBackground(new java.awt.Color(205, 51, 51));
        registrarse2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        registrarse2.setForeground(new java.awt.Color(255, 255, 255));
        registrarse2.setText("Regresar");
        registrarse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarse2ActionPerformed(evt);
            }
        });

        listadeplaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registrarse2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(listadeplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)))
                .addComponent(Lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listadeplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrarse2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarse2ActionPerformed
        this.setVisible(false);
        Bitacora.General("Usuario", "Preciono boton Regresar", "Error", "En DPI ingreso letras o no lo lleno");
    }//GEN-LAST:event_registrarse2ActionPerformed

    private void listadeplacaActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String placaSeleccionada = (String) listadeplaca.getSelectedItem();
        if (placaSeleccionada != null) {
            mostrarImagenVehiculo(placaSeleccionada); // Mostrar la imagen del vehículo seleccionado
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verautomovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verautomovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verautomovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verautomovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verautomovil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lblimagen;
    private javax.swing.JTable contenedordatos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listadeplaca;
    private javax.swing.JButton registrarse;
    private javax.swing.JButton registrarse1;
    private javax.swing.JButton registrarse2;
    // End of variables declaration//GEN-END:variables
}
